/**
 * Represents a proposed modification to a file generated by the AI.
 */
export interface CodeChange {
  /** Target file path */
  filePath: string;

  /** Current file content (or empty if new file) */
  originalContent: string;

  /** Proposed new content */
  newContent: string;

  /** Type of change */
  changeType: 'add' | 'modify' | 'delete';

  /** Unified diff format for display */
  diff: string;

  /** Affected line range (optional) */
  lineNumbers?: {
    start: number;
    end: number;
  };
}

/**
 * Create a CodeChange object.
 *
 * @param filePath - Target file path
 * @param originalContent - Current file content
 * @param newContent - Proposed new content
 * @param changeType - Type of change
 * @returns CodeChange object
 */
export function createCodeChange(
  filePath: string,
  originalContent: string,
  newContent: string,
  changeType: 'add' | 'modify' | 'delete' = 'modify'
): CodeChange {
  return {
    filePath,
    originalContent,
    newContent,
    changeType,
    diff: '', // Will be generated by FilePatcher
    lineNumbers: undefined,
  };
}
