/**
 * Represents a proposed modification to a file generated by the AI.
 * This is also referred to as CodeChange in some contexts.
 */
export interface CodeChangeProposal {
  /** Target file path */
  filePath: string;

  /** Current file content (or empty if new file) */
  originalContent: string;

  /** Proposed new content */
  newContent: string;

  /** Type of change */
  changeType: 'add' | 'modify' | 'delete';

  /** Unified diff format for display */
  diff: string;

  /** Affected line range (optional) */
  lineNumbers?: {
    start: number;
    end: number;
  };
}

/**
 * Type alias for compatibility with existing code
 */
export type CodeChange = CodeChangeProposal;

/**
 * Create a CodeChangeProposal object.
 *
 * @param filePath - Target file path
 * @param originalContent - Current file content
 * @param newContent - Proposed new content
 * @param changeType - Type of change
 * @returns CodeChangeProposal object
 */
export function createCodeChangeProposal(
  filePath: string,
  originalContent: string,
  newContent: string,
  changeType: 'add' | 'modify' | 'delete' = 'modify'
): CodeChangeProposal {
  return {
    filePath,
    originalContent,
    newContent,
    changeType,
    diff: '', // Will be generated by FilePatcher
    lineNumbers: undefined,
  };
}

/**
 * Legacy function name for compatibility
 */
export const createCodeChange = createCodeChangeProposal;

